version: "3.8"
services:
  backend:
    image: haltunbay/yacdbackend
    container_name: yacd.backend
    stdin_open: true
    tty: true
    ports:
      - 5000:80
  frontend:
    image: yacdfrontend:dev
    container_name: yacd.frontend
    stdin_open: true
    tty: true
    ports:
      - 5001:80
